"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import toast from "react-hot-toast";
import {
  getGitOpsStatus,
  createGitOpsExport,
  getGitOpsJobStatus,
  connectGitHub,
  listGitHubRepos,
  listGitHubBranches,
} from "@/lib/api";
import type {
  GitOpsConfig,
  GitOpsJobStatus,
  GitOpsBackendStatus,
  GitHubRepo,
  GitHubBranch,
} from "@/types/gitops";

interface GitOpsExportModalProps {
  exportId: string;
  flowName: string;
  onClose: () => void;
}

export default function GitOpsExportModal({ exportId, flowName, onClose }: GitOpsExportModalProps) {
  const [backendStatus, setBackendStatus] = useState<GitOpsBackendStatus | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [jobStatus, setJobStatus] = useState<GitOpsJobStatus | null>(null);

  // PAT setup state
  const [patInput, setPatInput] = useState("");
  const [isConnecting, setIsConnecting] = useState(false);

  // Repo search state
  const [repos, setRepos] = useState<GitHubRepo[]>([]);
  const [repoQuery, setRepoQuery] = useState("");
  const [repoDropdownOpen, setRepoDropdownOpen] = useState(false);
  const [isLoadingRepos, setIsLoadingRepos] = useState(false);
  const repoSearchTimer = useRef<ReturnType<typeof setTimeout>>();

  // Branch state
  const [branches, setBranches] = useState<GitHubBranch[]>([]);
  const [isLoadingBranches, setIsLoadingBranches] = useState(false);

  // Form state
  const [repo, setRepo] = useState("");
  const [baseBranch, setBaseBranch] = useState("main");
  const [branchName, setBranchName] = useState("");
  const [targetPath, setTargetPath] = useState("");
  const [prTitle, setPrTitle] = useState("");
  const [prBody, setPrBody] = useState("");
  const [dryRun, setDryRun] = useState(false);

  // Initialize form with defaults
  useEffect(() => {
    const slug = flowName.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    setBranchName(`agent/${slug}`);
    setPrTitle(`Add agent: ${flowName}`);
    setPrBody(`This PR adds the generated agent code for "${flowName}".\n\nGenerated by Zentro Forge.`);
  }, [flowName]);

  // Check backend status
  useEffect(() => {
    async function checkStatus() {
      try {
        const status = await getGitOpsStatus();
        setBackendStatus(status);
        if (status.default_repo) {
          setRepo(status.default_repo);
        }
      } catch {
        setBackendStatus({ configured: false });
      } finally {
        setIsLoading(false);
      }
    }
    checkStatus();
  }, []);

  const loadRepos = useCallback(async (query?: string) => {
    setIsLoadingRepos(true);
    try {
      const result = await listGitHubRepos(query);
      setRepos(result);
    } catch {
      // ignore
    } finally {
      setIsLoadingRepos(false);
    }
  }, []);

  const loadBranches = useCallback(async (fullName: string) => {
    const [owner, repoName] = fullName.split("/");
    if (!owner || !repoName) return;
    setIsLoadingBranches(true);
    try {
      const result = await listGitHubBranches(owner, repoName);
      setBranches(result);
      // Auto-select default branch from repo info
      const repoInfo = repos.find(r => r.full_name === fullName);
      if (repoInfo) {
        setBaseBranch(repoInfo.default_branch);
      }
    } catch {
      setBranches([]);
    } finally {
      setIsLoadingBranches(false);
    }
  }, [repos]);

  // Fetch repos when connected
  useEffect(() => {
    if (backendStatus?.configured) {
      loadRepos();
    }
  }, [backendStatus?.configured, loadRepos]);

  // Load branches when repo changes
  useEffect(() => {
    if (repo && repo.includes("/")) {
      loadBranches(repo);
    } else {
      setBranches([]);
    }
  }, [repo, loadBranches]);

  const handleRepoSearch = useCallback((value: string) => {
    setRepoQuery(value);
    if (repoSearchTimer.current) clearTimeout(repoSearchTimer.current);
    repoSearchTimer.current = setTimeout(() => {
      loadRepos(value || undefined);
    }, 300);
  }, [loadRepos]);

  const handleSelectRepo = useCallback((fullName: string) => {
    setRepo(fullName);
    setRepoQuery("");
    setRepoDropdownOpen(false);
  }, []);

  // Poll job status
  useEffect(() => {
    if (!jobStatus || jobStatus.status === "success" || jobStatus.status === "failed") {
      return;
    }

    const interval = setInterval(async () => {
      try {
        const status = await getGitOpsJobStatus(jobStatus.job_id);
        setJobStatus(status);
        if (status.status === "success") {
          toast.success("Pull request created successfully!");
        } else if (status.status === "failed") {
          toast.error(status.error_message || "Failed to create PR");
        }
      } catch {
        console.error("Failed to poll job status");
      }
    }, 2000);

    return () => clearInterval(interval);
  }, [jobStatus]);

  const handleConnect = async () => {
    if (!patInput.trim()) {
      toast.error("Please enter a GitHub token");
      return;
    }
    setIsConnecting(true);
    try {
      const result = await connectGitHub(patInput.trim());
      setBackendStatus({ configured: true, username: result.username });
      setPatInput("");
      toast.success(`Connected as @${result.username}`);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to connect");
    } finally {
      setIsConnecting(false);
    }
  };

  const handleSubmit = async () => {
    if (!repo.trim()) {
      toast.error("Repository is required");
      return;
    }

    const config: GitOpsConfig = {
      repo: repo.trim(),
      base_branch: baseBranch,
      branch_name: branchName,
      target_path: targetPath || undefined,
      pr_title: prTitle,
      pr_body: prBody,
      dry_run: dryRun,
    };

    setIsSubmitting(true);
    try {
      const response = await createGitOpsExport(exportId, config);
      setJobStatus({
        job_id: response.job_id,
        export_id: exportId,
        status: response.status,
        logs: [],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      });
      toast.success(dryRun ? "Dry run started" : "Creating pull request...");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to start GitOps export");
    } finally {
      setIsSubmitting(false);
    }
  };

  if (isLoading) {
    return (
      <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 backdrop-blur-sm">
        <div
          className="rounded-xl shadow-2xl p-8 border"
          style={{
            backgroundColor: "var(--bg-secondary)",
            borderColor: "var(--border-default)",
          }}
        >
          <div className="flex items-center gap-3 text-[var(--text-muted)]">
            <svg className="w-5 h-5 animate-spin" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
            Checking GitHub integration...
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 backdrop-blur-sm">
      <div
        className="rounded-xl shadow-2xl w-full max-w-lg mx-4 border"
        style={{
          backgroundColor: "var(--bg-secondary)",
          borderColor: "var(--border-default)",
        }}
      >
        {/* Header */}
        <div
          className="p-4 border-b flex items-center justify-between"
          style={{ borderColor: "var(--border-default)" }}
        >
          <div className="flex items-center gap-2">
            <svg className="w-5 h-5 text-white" fill="currentColor" viewBox="0 0 24 24">
              <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z" />
            </svg>
            <h2 className="text-lg font-semibold text-white">Open PR to GitHub</h2>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-md transition-colors hover:bg-[var(--bg-tertiary)]"
            style={{ color: "var(--text-muted)" }}
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Content */}
        <div className="p-6 max-h-[60vh] overflow-y-auto">
          {!backendStatus?.configured ? (
            /* PAT setup form */
            <div className="space-y-4">
              <div className="text-center">
                <div className="w-16 h-16 mx-auto mb-4 rounded-xl bg-[var(--bg-tertiary)] flex items-center justify-center">
                  <svg className="w-8 h-8 text-[var(--text-secondary)]" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z" />
                  </svg>
                </div>
                <h3 className="text-white font-medium mb-2">Connect GitHub</h3>
                <p className="text-sm text-[var(--text-muted)] mb-4">
                  Enter a Personal Access Token with <code className="text-xs bg-[var(--bg-tertiary)] px-1 py-0.5 rounded">repo</code> scope to create pull requests.
                </p>
              </div>

              {/* How-to steps */}
              <div
                className="rounded-lg p-3 text-xs space-y-2"
                style={{ backgroundColor: "var(--bg-tertiary)" }}
              >
                <p className="text-[var(--text-secondary)] font-medium">How to create a token:</p>
                <ol className="list-decimal list-inside space-y-1 text-[var(--text-muted)]">
                  <li>Go to <a href="https://github.com/settings/tokens/new" target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:underline">GitHub Token Settings</a></li>
                  <li>Give it a descriptive name (e.g. &quot;Zentro Forge&quot;)</li>
                  <li>Select the <code className="bg-[var(--bg-secondary)] px-1 py-0.5 rounded">repo</code> scope (full control of private repositories)</li>
                  <li>Click <strong className="text-[var(--text-secondary)]">Generate token</strong> and copy it below</li>
                </ol>
              </div>

              <div>
                <label className="block text-xs font-medium text-[var(--text-secondary)] mb-1.5">
                  Personal Access Token
                </label>
                <input
                  type="password"
                  value={patInput}
                  onChange={(e) => setPatInput(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleConnect()}
                  className="input-field w-full"
                  placeholder="ghp_xxxxxxxxxxxxxxxxxxxx"
                  autoFocus
                />
              </div>

              <button
                onClick={handleConnect}
                disabled={isConnecting || !patInput.trim()}
                className="btn-pill w-full"
              >
                {isConnecting ? (
                  <span className="flex items-center justify-center gap-2">
                    <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                    Connecting...
                  </span>
                ) : (
                  "Connect to GitHub"
                )}
              </button>
            </div>
          ) : jobStatus ? (
            <JobStatusView status={jobStatus} />
          ) : (
            <div className="space-y-4">
              {/* Connected status */}
              {backendStatus.username && (
                <div className="flex items-center gap-2 p-2 rounded-lg bg-green-500/10 border border-green-500/20 text-xs text-green-400">
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                  Connected as @{backendStatus.username}
                </div>
              )}

              {/* Warning */}
              <div className="p-3 rounded-lg bg-amber-500/10 border border-amber-500/20">
                <div className="flex items-start gap-2 text-amber-400 text-xs">
                  <svg className="w-4 h-4 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                  </svg>
                  <span>
                    This will create a branch and PR in your repository.
                    Ensure you have write access to the target repo.
                  </span>
                </div>
              </div>

              {/* Repository — searchable dropdown */}
              <div className="relative">
                <label className="block text-xs font-medium text-[var(--text-secondary)] mb-1.5">
                  Repository
                </label>
                {repo ? (
                  <div className="flex items-center gap-2">
                    <div
                      className="flex-1 px-3 py-2 rounded-lg text-sm text-white border"
                      style={{
                        backgroundColor: "var(--bg-tertiary)",
                        borderColor: "var(--border-default)",
                      }}
                    >
                      {repo}
                    </div>
                    <button
                      onClick={() => { setRepo(""); setRepoDropdownOpen(true); }}
                      className="px-2 py-2 text-xs text-[var(--text-muted)] hover:text-white transition-colors"
                    >
                      Change
                    </button>
                  </div>
                ) : (
                  <>
                    <input
                      type="text"
                      value={repoQuery}
                      onChange={(e) => handleRepoSearch(e.target.value)}
                      onFocus={() => setRepoDropdownOpen(true)}
                      className="input-field w-full"
                      placeholder="Search repositories..."
                    />
                    {repoDropdownOpen && (
                      <div
                        className="absolute z-10 left-0 right-0 mt-1 rounded-lg border shadow-xl max-h-48 overflow-y-auto"
                        style={{
                          backgroundColor: "var(--bg-tertiary)",
                          borderColor: "var(--border-default)",
                        }}
                      >
                        {isLoadingRepos ? (
                          <div className="p-3 text-xs text-[var(--text-muted)] text-center">Loading...</div>
                        ) : repos.length === 0 ? (
                          <div className="p-3 text-xs text-[var(--text-muted)] text-center">No repositories found</div>
                        ) : (
                          repos.map((r) => (
                            <button
                              key={r.full_name}
                              onClick={() => handleSelectRepo(r.full_name)}
                              className="w-full text-left px-3 py-2 text-sm hover:bg-[var(--bg-secondary)] transition-colors flex items-center justify-between"
                            >
                              <span className="text-white">{r.full_name}</span>
                              <span className="text-xs text-[var(--text-muted)]">
                                {r.private ? "Private" : "Public"}
                              </span>
                            </button>
                          ))
                        )}
                      </div>
                    )}
                  </>
                )}
              </div>

              {/* Branches */}
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-medium text-[var(--text-secondary)] mb-1.5">
                    Base Branch
                  </label>
                  {branches.length > 0 ? (
                    <select
                      value={baseBranch}
                      onChange={(e) => setBaseBranch(e.target.value)}
                      className="input-field w-full"
                    >
                      {branches.map((b) => (
                        <option key={b.name} value={b.name}>{b.name}</option>
                      ))}
                    </select>
                  ) : (
                    <input
                      type="text"
                      value={baseBranch}
                      onChange={(e) => setBaseBranch(e.target.value)}
                      className="input-field w-full"
                    />
                  )}
                  {isLoadingBranches && (
                    <p className="text-xs text-[var(--text-muted)] mt-1">Loading branches...</p>
                  )}
                </div>
                <div>
                  <label className="block text-xs font-medium text-[var(--text-secondary)] mb-1.5">
                    New Branch Name
                  </label>
                  <input
                    type="text"
                    value={branchName}
                    onChange={(e) => setBranchName(e.target.value)}
                    className="input-field w-full"
                  />
                </div>
              </div>

              {/* Target Path */}
              <div>
                <label className="block text-xs font-medium text-[var(--text-secondary)] mb-1.5">
                  Target Path (optional)
                </label>
                <input
                  type="text"
                  value={targetPath}
                  onChange={(e) => setTargetPath(e.target.value)}
                  className="input-field w-full"
                  placeholder="e.g., agents/my-agent"
                />
              </div>

              {/* PR Title */}
              <div>
                <label className="block text-xs font-medium text-[var(--text-secondary)] mb-1.5">
                  PR Title
                </label>
                <input
                  type="text"
                  value={prTitle}
                  onChange={(e) => setPrTitle(e.target.value)}
                  className="input-field w-full"
                />
              </div>

              {/* PR Body */}
              <div>
                <label className="block text-xs font-medium text-[var(--text-secondary)] mb-1.5">
                  PR Description
                </label>
                <textarea
                  value={prBody}
                  onChange={(e) => setPrBody(e.target.value)}
                  className="input-field w-full min-h-[80px] resize-y"
                />
              </div>

              {/* Dry Run Toggle */}
              <label className="flex items-center gap-3 cursor-pointer">
                <div className="relative">
                  <input
                    type="checkbox"
                    checked={dryRun}
                    onChange={(e) => setDryRun(e.target.checked)}
                    className="sr-only peer"
                  />
                  <div className="w-10 h-5 bg-[var(--bg-tertiary)] rounded-full peer peer-checked:bg-cyan-500 transition-colors border border-[var(--border-default)]" />
                  <div className="absolute left-0.5 top-0.5 w-4 h-4 bg-white rounded-full transition-transform peer-checked:translate-x-5" />
                </div>
                <div>
                  <span className="text-sm text-[var(--text-secondary)]">Dry Run</span>
                  <p className="text-xs text-[var(--text-muted)]">Validate without creating the PR</p>
                </div>
              </label>
            </div>
          )}
        </div>

        {/* Footer */}
        {backendStatus?.configured && !jobStatus && (
          <div
            className="p-4 border-t flex gap-3"
            style={{ borderColor: "var(--border-default)" }}
          >
            <button onClick={onClose} className="btn-secondary flex-1" disabled={isSubmitting}>
              Cancel
            </button>
            <button onClick={handleSubmit} className="btn-pill flex-1" disabled={isSubmitting || !repo}>
              {isSubmitting ? (
                <span className="flex items-center justify-center gap-2">
                  <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  Submitting...
                </span>
              ) : dryRun ? (
                "Run Validation"
              ) : (
                "Create PR"
              )}
            </button>
          </div>
        )}

        {!backendStatus?.configured && (
          <div
            className="p-4 border-t"
            style={{ borderColor: "var(--border-default)" }}
          >
            <button onClick={onClose} className="btn-secondary w-full">
              Cancel
            </button>
          </div>
        )}

        {jobStatus && (
          <div
            className="p-4 border-t"
            style={{ borderColor: "var(--border-default)" }}
          >
            <button onClick={onClose} className="btn-secondary w-full">
              Close
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

function JobStatusView({ status }: { status: GitOpsJobStatus }) {
  return (
    <div className="space-y-4">
      {/* Status Header */}
      <div className="flex items-center gap-3">
        {status.status === "success" ? (
          <div className="w-10 h-10 rounded-full bg-green-500/20 flex items-center justify-center">
            <svg className="w-5 h-5 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
            </svg>
          </div>
        ) : status.status === "failed" ? (
          <div className="w-10 h-10 rounded-full bg-red-500/20 flex items-center justify-center">
            <svg className="w-5 h-5 text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </div>
        ) : (
          <div className="w-10 h-10 rounded-full bg-[var(--bg-tertiary)] flex items-center justify-center">
            <svg className="w-5 h-5 text-[var(--text-muted)] animate-spin" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
          </div>
        )}
        <div>
          <h3 className="text-white font-medium capitalize">{status.status}</h3>
          <p className="text-xs text-[var(--text-muted)]">
            {status.status === "running" ? "Creating pull request..." :
             status.status === "success" ? "Pull request created" :
             status.status === "failed" ? "Failed to create PR" : "Pending"}
          </p>
        </div>
      </div>

      {/* PR Link */}
      {status.pr_url && (
        <a
          href={status.pr_url}
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-2 p-3 rounded-lg bg-green-500/10 border border-green-500/20 text-green-400 hover:bg-green-500/20 transition-colors"
        >
          <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
            <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z" />
          </svg>
          <span className="flex-1">View Pull Request #{status.pr_number}</span>
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
          </svg>
        </a>
      )}

      {/* Error */}
      {status.error_message && (
        <div className="p-3 rounded-lg bg-red-500/10 border border-red-500/20">
          <p className="text-sm text-red-400">{status.error_message}</p>
        </div>
      )}

      {/* Logs */}
      {status.logs.length > 0 && (
        <div>
          <h4 className="text-xs font-medium text-[var(--text-muted)] mb-2">Logs</h4>
          <div
            className="rounded-lg p-3 max-h-40 overflow-y-auto font-mono text-xs"
            style={{ backgroundColor: "var(--bg-tertiary)" }}
          >
            {status.logs.map((log, i) => (
              <div key={i} className="text-[var(--text-secondary)]">{log}</div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
